In [1]:
import numpy as np

# arange()

### 用法1:  arange(end)  

In [ ]:
np.arange(3)

### 用法2: arange(start, end)

In [ ]:
np.arange(3, 10)

### 用法3: arange(start, end, step)
### step可以是整数，也可以是小数

In [ ]:
np.arange(3, 10, 2)

In [ ]:
np.arange(2, 5, 0.2)

# array()

#### 用法是可以把列表放到括号里面生成ndarray

In [ ]:
np.array([1, 2, 3])


In [ ]:
np.array([
         [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
         [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
         ]
        )

# asarray()

### 用法：numpy.array dtype可选

In [ ]:
x = [1, 2, 3]

In [18]:
a = np.asarray(x)

In [20]:
a

array([(1, 2, 3), (4, 5)], dtype=object)

In [10]:
x = (1, 2, 3)

In [11]:
a = np.asarray(x)

In [12]:
a

array([1, 2, 3])

In [14]:
x = [(1, 2, 3), (4, 5)]

In [15]:
a = np.asarray(x)

In [21]:
a

array([(1, 2, 3), (4, 5)], dtype=object)

In [22]:
x = [1, 2, 3]

In [23]:
a = np.asarray(x, dtype=float)

In [24]:
a

array([1., 2., 3.])

# reshape()

### 用法reshape(shape)
### shape既可以是reshape(3, 5)
### shape也可以是reshape((3, 5))

In [ ]:
a = np.arange(15)

In [ ]:
a.reshape(3, 5)

# empty

### 用法
### 数组元素为随机值，因为它们未初始化, dtype为可选

In [ ]:
x = np.empty([3, 2], dtype=int)

In [ ]:
x

# linspace()

### 用法 np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
### 该值为 true 时，数列中中包含stop值，反之不包含，默认是True

In [44]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [47]:
a = np.linspace(2, 2, 10)

In [48]:
a

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [6]:
a = np.linspace(10, 20, 5, endpoint=False)

In [5]:
a

array([10. , 12.5, 15. , 17.5, 20. ])

In [8]:
a = np.linspace(1, 10, 10, retstep=True)

In [9]:
a

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)

In [10]:
b = np.linspace(1, 10, 10).reshape([10, 1])

In [11]:
b

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

# ndarray的属性

In [ ]:
a = np.arange(16).reshape(2, 2, 4)

### shape

In [ ]:
a.shape

### size

In [ ]:
a.size

### ndim 表示轴的数量，数组的维数

In [ ]:
a.ndim

### dtype 表述数据类型
### 后面加个name直接提取出名称

In [ ]:
a.dtype

In [ ]:
a.dtype.name

### itemsize 元素字节大小 (还没完全搞懂)

In [ ]:
a.itemsize

# ones()

### 创建指定形状的数组，数组元素以 1 来填充, dtype可选 

In [ ]:
np.ones(5)

In [ ]:
np.ones([4, 2, 3], dtype=int)

# zeros()

### 用法：创建指定大小的数组，数组元素以 0 来填充,dtype可选,默认为浮点数

In [ ]:
x = np.zeros(5)

In [ ]:
x

In [ ]:
y = np.zeros((5, 2), dtype=np.int)

In [ ]:
y

In [36]:
x = np.arange(5)

In [125]:
x

array([10, 12, 14, 16, 18, 20])

In [1]:
import numpy as np

In [2]:
a = np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
s = slice(2, 7)

In [8]:
s

slice(2, 7, None)

In [9]:
a[s]

array([2, 3, 4, 5, 6])

In [13]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
b = a[5:]
b

array([5, 6, 7, 8, 9])

array([2, 3, 4, 5, 6])

In [19]:
a = np.arange(10)

In [20]:
a[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
a = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])

In [22]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [27]:
a[0:2]

array([[1, 2, 3],
       [3, 4, 5]])

In [28]:
a[..., 1]

array([2, 4, 5])

In [29]:
a[1, ...]

array([3, 4, 5])

In [30]:
a[..., 1:]

array([[2, 3],
       [4, 5],
       [5, 6]])

In [31]:
x = np.array([[1, 2], [3, 4], [5, 6]])

In [32]:
y = x[[0, 1, 2], [0, 1, 0]]

In [33]:
y

array([1, 4, 5])

In [34]:
x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])

In [35]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [37]:
rows = np.array([[0, 0], [3, 3]])

In [38]:
cols = np.array([[0, 2], [0, 2]])

In [39]:
y = x[rows, cols]

In [40]:
y

array([[ 0,  2],
       [ 9, 11]])

In [41]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [42]:
b = a[1:3, 1:3]

In [43]:
c = a[1:3, [1, 2]]

In [44]:
d = a[..., 1:]

In [45]:
b

array([[5, 6],
       [8, 9]])

In [46]:
c

array([[5, 6],
       [8, 9]])

In [47]:
d

array([[2, 3],
       [5, 6],
       [8, 9]])

In [51]:
x = np.array([[70, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])

In [52]:
x

array([[70,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [53]:
x[x > 5]

array([70,  6,  7,  8,  9, 10, 11])

In [54]:
a = np.array([np.nan, 1, 2, np.nan, 3, 4, 5])

In [55]:
a[~np.isnan(a)]

array([1., 2., 3., 4., 5.])

In [56]:
a = np.array([1, 2+6j, 5, 3.5+5j])

In [58]:
a[np.iscomplex(a)]

array([2. +6.j, 3.5+5.j])

In [61]:
x = np.arange(32).reshape(8, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [60]:
x[[4, 2, 1, 7]]

array([[16, 17, 18, 19],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [28, 29, 30, 31]])

In [63]:
x = np.arange(32).reshape(8, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [64]:
x[[-4, -2, -1, -7]]

array([[16, 17, 18, 19],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [ 4,  5,  6,  7]])

In [65]:
x = np.arange(32).reshape(8, 4)

In [66]:
x[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [67]:
a = np.array([1, 2, 3, 4])

In [68]:
b = np.array([10, 20, 30, 40])

In [69]:
c = a * b

In [70]:
c

array([ 10,  40,  90, 160])

In [71]:
a = np.array([[0, 0, 0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])

In [72]:
b = np.array([1, 2, 3])

In [73]:
a + b 

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [74]:
a = np.array([[0, 0, 0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])

In [75]:
b = np.array([1, 2, 3])

In [76]:
bb = np.tile(b, (4, 1))

In [77]:
a + bb

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [78]:
a = np.arange(6).reshape(2, 3)

In [79]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [80]:
for x in np.nditer(a):
    print(x, end=', ')

0, 1, 2, 3, 4, 5, 

In [81]:
a = np.arange(6).reshape(2, 3)

In [82]:
for x in np.nditer(a.T):
    print(x, end=',-')

0,-1,-2,-3,-4,-5,-

In [83]:
for x in np.nditer(a.T.copy(order='C')):
    print(x, end=', ')

0, 3, 1, 4, 2, 5, 

In [84]:
a = np.arange(0, 60, 5)

In [85]:
a = a.reshape(3, 4)

In [86]:
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [87]:
b = a.T

In [88]:
b

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [93]:
c = b.copy(order='C')

In [94]:
c

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [95]:
for x in np.nditer(c):
    print(x, end=', ')

0, 20, 40, 5, 25, 45, 10, 30, 50, 15, 35, 55, 

In [96]:
c = b.copy(order='F')

In [97]:
c

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [98]:
for x in np.nditer(c):
    print(x, end=', ')

0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 

In [99]:
a = np.arange(0, 60, 5)

In [100]:
a = a.reshape(3, 4)

In [101]:
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [102]:
for x in np.nditer(a, order='C'):
    print(x, end=', ')

0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 

In [103]:
for x in np.nditer(a, order='F'):
    print(x, end=', ')

0, 20, 40, 5, 25, 45, 10, 30, 50, 15, 35, 55, 

In [ ]:
https://www.runoob.com/numpy/numpy-terating-over-array.html
    修改数组中元素的值