In [1]:
import numpy as np

# arange()

### 用法1:  arange(end)  

In [2]:
np.arange(3)

array([0, 1, 2])

### 用法2: arange(start, end)

In [3]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

### 用法3: arange(start, end, step)
### step可以是整数，也可以是小数

In [4]:
np.arange(3, 10, 2)

array([3, 5, 7, 9])

In [5]:
np.arange(2, 5, 0.2)

# array()

#### 用法是可以把列表放到括号里面生成ndarray

In [42]:
np.array([1, 2, 3])


array([1, 2, 3])

In [38]:
np.array([
         [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
         [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
         ]
        )

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

# reshape()

### 用法reshape(shape)
### shape既可以是reshape(3, 5
### shape也可以是reshape((3, 5))

In [6]:
a = np.arange(15)

In [7]:
a.reshape(3, 5)

# empty

### 用法
### 数组元素为随机值，因为它们未初始化, dtype为可选

In [93]:
x = np.empty([3, 2], dtype=int)

In [95]:
x

array([[1919295603,  170814831],
       [ 538976288,  538976288],
       [1716068397, 1769496864]])

# ndarray的属性

In [64]:
a = np.arange(16).reshape(2, 2, 4)

### shape

In [66]:
a.shape

(2, 2, 4)

### size

In [72]:
a.size

16

### ndim 表示轴的数量，数组的维数

In [10]:
a.ndim

3

### dtype 表述数据类型
### 后面加个name直接提取出名称

In [11]:
a.dtype

dtype('int32')

In [12]:
a.dtype.name

'int32'

### itemsize 元素字节大小 (还没完全搞懂)

In [13]:
a.itemsize

4

# zeros()

### 用法：创建指定大小的数组，数组元素以 0 来填充,dtype可选,默认为浮点数

In [96]:
x = np.zeros(5)

In [97]:
x

array([0., 0., 0., 0., 0.])

In [100]:
y = np.zeros((5, 2), dtype=np.int)

In [104]:
y

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [ ]:
https://www.runoob.com/numpy/numpy-array-creation.html

# 自定义类型
z = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(z)