In [3]:
import numpy as np

# arange()

### 用法1:  arange(end)  

In [4]:
np.arange(3)

array([0, 1, 2])

### 用法2: arange(start, end)

In [5]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

### 用法3: arange(start, end, step)
### step可以是整数，也可以是小数

In [6]:
np.arange(3, 10, 2)

array([3, 5, 7, 9])

In [7]:
np.arange(2, 5, 0.2)

array([2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4,
       4.6, 4.8])

# reshape()

### 用法reshape(shape)
### shape既可以是reshape(3, 5
### shape也可以是reshape((3, 5))

In [8]:
a = np.arange(15)

In [9]:
a.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# ndarray的属性

In [14]:
a = np.arange(16).reshape(2, 2, 4)

### shape

In [16]:
a.shape

(2, 2, 4)

### ndim 表示轴的数量，数组的维数

In [15]:
a.ndim

3

### dtype 表述数据类型
### 后面加个name直接提取出名称

In [20]:
a.dtype

dtype('int32')

In [21]:
a.dtype.name

'int32'

### itemsize 元素字节大小 (还没完全搞懂)

In [22]:
a.itemsize

4