In [9]:
import numpy as np

# arange()

### 用法1:  arange(end)  

In [10]:
np.arange(3)

array([0, 1, 2])

### 用法2: arange(start, end)

In [11]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

### 用法3: arange(start, end, step)
### step可以是整数，也可以是小数

In [12]:
np.arange(3, 10, 2)

array([3, 5, 7, 9])

In [13]:
np.arange(2, 5, 0.2)

array([2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4,
       4.6, 4.8])

# reshape()

### 用法reshape(shape)
### shape既可以是reshape(3, 5
### shape也可以是reshape((3, 5))

In [16]:
a = np.arange(15)

In [17]:
a.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# ndarray的属性

In [19]:
a = np.arange(15).reshape(3, 5)

### shape

In [20]:
a.shape

(3, 5)