In [1]:
import numpy as np

# arange()

### 用法1:  arange(end)  

In [ ]:
np.arange(3)

### 用法2: arange(start, end)

In [ ]:
np.arange(3, 10)

### 用法3: arange(start, end, step)
### step可以是整数，也可以是小数

In [ ]:
np.arange(3, 10, 2)

In [ ]:
np.arange(2, 5, 0.2)

# array()

#### 用法是可以把列表放到括号里面生成ndarray

In [ ]:
np.array([1, 2, 3])


In [ ]:
np.array([
         [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
         [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
         ]
        )

# asarray()

### 用法：numpy.array dtype可选

In [ ]:
x = [1, 2, 3]

In [18]:
a = np.asarray(x)

In [20]:
a

array([(1, 2, 3), (4, 5)], dtype=object)

In [10]:
x = (1, 2, 3)

In [11]:
a = np.asarray(x)

In [12]:
a

array([1, 2, 3])

In [14]:
x = [(1, 2, 3), (4, 5)]

In [15]:
a = np.asarray(x)

In [21]:
a

array([(1, 2, 3), (4, 5)], dtype=object)

In [22]:
x = [1, 2, 3]

In [23]:
a = np.asarray(x, dtype=float)

In [24]:
a

array([1., 2., 3.])

# reshape()

### 用法reshape(shape)
### shape既可以是reshape(3, 5)
### shape也可以是reshape((3, 5))

In [ ]:
a = np.arange(15)

In [ ]:
a.reshape(3, 5)

# empty

### 用法
### 数组元素为随机值，因为它们未初始化, dtype为可选

In [ ]:
x = np.empty([3, 2], dtype=int)

In [ ]:
x

# linspace()

### 用法 np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
### 该值为 true 时，数列中中包含stop值，反之不包含，默认是True

In [44]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [47]:
a = np.linspace(2, 2, 10)

In [48]:
a

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [6]:
a = np.linspace(10, 20, 5, endpoint=False)

In [5]:
a

array([10. , 12.5, 15. , 17.5, 20. ])

In [8]:
a = np.linspace(1, 10, 10, retstep=True)

In [9]:
a

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)

In [10]:
b = np.linspace(1, 10, 10).reshape([10, 1])

In [11]:
b

array([[ 1.],
       [ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.]])

# ndarray的属性

In [ ]:
a = np.arange(16).reshape(2, 2, 4)

### shape

In [ ]:
a.shape

### size

In [ ]:
a.size

### ndim 表示轴的数量，数组的维数

In [ ]:
a.ndim

### dtype 表述数据类型
### 后面加个name直接提取出名称

In [ ]:
a.dtype

In [ ]:
a.dtype.name

### itemsize 元素字节大小 (还没完全搞懂)

In [ ]:
a.itemsize

# ones()

### 创建指定形状的数组，数组元素以 1 来填充, dtype可选 

In [ ]:
np.ones(5)

In [ ]:
np.ones([4, 2, 3], dtype=int)

# zeros()

### 用法：创建指定大小的数组，数组元素以 0 来填充,dtype可选,默认为浮点数

In [ ]:
x = np.zeros(5)

In [ ]:
x

In [ ]:
y = np.zeros((5, 2), dtype=np.int)

In [ ]:
y

In [36]:
x = np.arange(5)

In [37]:
x

array([0, 1, 2, 3, 4])

In [ ]:
https://www.runoob.com/numpy/numpy-array-manipulation.html
    arr：输入数组
obj：在其之前插入值的索引
values：要插入的值
axis：沿着它插入的轴，如果未提供，则输入数组会被展开